vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        magazines:
            uri_prefix: /images/upload/covers
            upload_destination: '%kernel.project_dir%/public/images/upload/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
